### ISSUE TITLE
Spigot 1.13.1 with Ridables 2.34 crashes Ridables

### ISSUE THREAD

**Issue by smmmadden** [BillyGalbreath/Ridables#11]
Spigot just released the 1.13.1 server and I was testing to see which plugins break because of the latest bug fixes.  Unfortunately many of them crashed again.  Here is the log entry for today.
![image](https://user-images.githubusercontent.com/10309346/44627851-0cd3c000-a903-11e8-8cb5-38271ba5fa5f.png)

**Comment by BillyGalbreath** [comment]
This is expected because its a full NMS version change (1_13_R1->1_13_R2). Developers using NMS are well aware of the situation ;)
