### ISSUE TITLE
Permissons

### ISSUE THREAD

**Issue by Castiella** [BillyGalbreath/Ridables#14]
It would be super cool if you could possibly add permissions? we want to restrict ridables for low/bad rep groups. 

for example ridables.teleportwithmob and also ridables.ride.dolphin. 

Really grateful for the free resource!

**Comment by BillyGalbreath** [comment]
https://github.com/BillyGalbreath/Ridables/blob/master/src/main/resources/plugin.yml#L17-L234

Also this is a WIP: https://github.com/BillyGalbreath/Ridables/wiki/Mobs
