### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by Castiella** [BillyGalbreath/Ridables#16]
Hi, 

When i set the config to true for dolphins, you can ride the dolphins fine, but when i edit any other mob to be rideable it stops the whole plugin working. no errors/output on console.

Is there an issue with my config?

[config.yml.txt](https://github.com/BillyGalbreath/Ridables/files/2364237/config.yml.txt)

**Comment by Castiella** [comment]
Also nobody can ride horses lol

**Comment by Castiella** [comment]
Okay, so i changed dolphin to true after resetting the config, and it will allow you to ride dolphins, but when you try and get on a horse it throws you back.

**Comment by smmmadden** [comment]
horses have to be tamed first before you can saddle them.  That's vanilla MC.  So you right click the horse without a saddle and you get on top.  You may have to repeat several times (on/off) until you see the hearts from the horse.  Then you can right click the horse with the saddle, add the saddle and then can mount it.

**Comment by Castiella** [comment]
I have owned a server for 4 years and am very aware of how vanilla mc works. 

You are not able to tame horses at all because you can not ride them. 

This is also happening with tamed horses. 

When I remove the plugin all horses can be ridden again.

**Comment by smmmadden** [comment]
make sure it is enabled in the config and you have the permission.  I'm using PaperSpigot build 229 (1.13.1) and Ridables 2.43 and can mount horses.  If that's not it, can you provide a list of plugins as there could be a conflict with another one.

**Comment by Castiella** [comment]
Yes it is configurated properly and enabled, I’ll grab a list of plugins when I’m home

**Comment by Castiella** [comment]
Just to clarify, i was a few builds behind on paper by the looks of it, as i updated to 229 and not having the issue anymore, thank you
