### ISSUE TITLE
squids and guardians cant bee collected

### ISSUE THREAD

**Issue by Castiella** [BillyGalbreath/Ridables#17]
Hi! Please could you add these to the plugin so players can collect them? If they're supposed to be there - its not working.

Thank you so much :)

**Comment by BillyGalbreath** [comment]
Squids should be collectible in the latest release. I'll add the other water mobs in v3 ^_^

**Comment by BillyGalbreath** [comment]
All water mobs are now collectible in v3 alpha4 (dolphin, elder_guardian, guardian, squid, and turtle). \o/
