### ISSUE TITLE
players take damage when riding drowned

### ISSUE THREAD

**Issue by Castiella** [BillyGalbreath/Ridables#18]
literally as above, lol. players take damage when riding drowned. Hope this is something that can be fixed, but not a huge issue

:)

**Comment by BillyGalbreath** [comment]
Yikes! That's no fun :(

I'll be sure to get this fixed in the upcoming v3 rewrite. ^_^

Edit: Just verified the bug. It is with the AI still wanting to target the riding player. This is fixed in v3. Will mark ticket solved when v3 is released.

**Comment by Castiella** [comment]
Thanks a bunch Billy :)

**Comment by BillyGalbreath** [comment]
This is fixed in v3 alpha builds. \o/
