### ISSUE TITLE
Bucket gets consumed.

### ISSUE THREAD

**Issue by InflamedSebi** [BillyGalbreath/Ridables#2]
Releasing a caught turtle consumes the bucket.
This feels wrong to me, is there an option to turn this off, or is this a bug in general?

**Comment by BillyGalbreath** [comment]
Definitely a bug. Just a simple oversight on my part. Will be fixed next release ^_^

**Comment by BillyGalbreath** [comment]
Ok, while attempting to fix this I've come across another issue. ~~So, I'm going to leave it as-is for now and re-visit this after my bug report to Spigot Jira is taken care of.~~ Changed my mind. Updating now, will worry about md_5 fixing the new visual desync bug later.

https://hub.spigotmc.org/jira/browse/SPIGOT-4238

**Comment by BillyGalbreath** [comment]
Ok, the visual desync bug was fixed. Be sure to update your server software and grab v2.8.2 of the plugin ^_^
