### ISSUE TITLE
Charged Jumps Request

### ISSUE THREAD

**Issue by CaliDreams** [BillyGalbreath/Ridables#20]
(new to all of this so I'm not sure if this is where to post this suggestion - copied from Spigot)

I'm very new to server ownership and plugins file-side so forgive me if I'm taking a shot in the dark here!
I adore your plugin and adore even more now that it is compatible with Safarinets (I may or may not have been the one to accidentally kick off that conversation)

I modified all the mobs in speed and jump, I wanted them to be donator rewards that would be just as exciting if not more exciting to ride around on the different kinds of mobs than just horses. However doing so, apparently once I modified the jumps, player's animals were able to jump over fences. Is it possible to make a jump modifier that would only go into effect if the mob was mounted? And they'd default back to a 1 block high (or two blocks high in the case of rabbit) vanilla settings? Or what if, if it's possible, even better, you could add a "charged jump" like the horse and I think slime and magma blocks already have, to the rest of the mobs? And add an option for "max block jump height modifier?"

**Comment by BillyGalbreath** [comment]
Added a bunch of configuration options in v3 alpha builds, including separating riding and AI tweaks (such as jump heights) \o/

**Comment by CaliDreams** [comment]
Awesome, thank you so much!
