### ISSUE TITLE
Server crash upon login - Ticking entity?

### ISSUE THREAD

**Issue by CaliDreams** [BillyGalbreath/Ridables#27]
Running Spigot 1.13.2 with Rideables 2.56
Console errors before crash:
https://pastebin.com/GU7tKKWf

**Comment by BillyGalbreath** [comment]
Spigot changed their nms mappings recently which broke every plugin that uses nms. Temporary fix is to downgrade your server software until I can push out an updated plugin build. v2.x is pretty low on my priority list, though.

**Comment by CaliDreams** [comment]
Ok, thanks

**Comment by BillyGalbreath** [comment]
Just wanted to touch base to let you know I haven't forgotten about this. Just been busy. Well, side tracked is a better word (been making Skyrim mods).

I'll try to set some time this week for this. No promises, though.

**Comment by CaliDreams** [comment]
Ty for kindly getting back about this, my donators have been asking. We love your plugin and miss it! I understand being busy. The holidays were especially crazy for me and a lot was on hold.

**Comment by BillyGalbreath** [comment]
Closing this as "wont fix" because I have officially dropped support for Spigot and CraftBukkit.

Update to [Ridables v3.0](https://papermc.io/forums/t/1-13-2-ridables-ride-and-control-any-mob-with-full-wasd-controls/102) and switch over to [Paper build 568+](https://papermc.io/downloads)
