### ISSUE TITLE
Mount/Unmount API events

### ISSUE THREAD

**Issue by BillyGalbreath** [BillyGalbreath/Ridables#4]

**Comment by Lix3nn53** [comment]
Thanks for this!

Also I need a method with mount and player paramaters that simply mounts the player,
Or would vanilla method mounting would work?

**Comment by BillyGalbreath** [comment]
See my updated response on SpigotMC site: https://www.spigotmc.org/threads/1-13-ridables.330108/page-7#post-3109318

As for mounting the player, you can use the Bukkit-API method Entity#addPassenger(Entity). You can already do this for any Entity, but only my Ridable entities have WASD controls.
