### ISSUE TITLE
Option to require shift + right click to ride to avoid right click interactions with mobs breaking.

### ISSUE THREAD

**Issue by mibby** [BillyGalbreath/Ridables#43]
Would it be possible to add an option to require ``shift + right click`` to ride? With ridables interacting on right click only, it's causing a few problems;

1) Breaking all mobs that have right click interactables, requiring players to ``shift + right click`` to use vanilla behavior.

i.e. needing to ``shift + right click`` to shear sheep or ``shift + right click`` to open villager trade windows.

2) Spamming you with messages telling you that you require a saddle every time you interact with a mob. (Few players complained this was a bit annoying.)

Forcing Ridables to only work when players ``shift + right click`` should solve both of these issues, as it would require you to intentionally use a method for you to do intended behavior rather than overwrite vanilla ones.

**Comment by BillyGalbreath** [comment]
Unfortunately, that's not a possibility. See #6

The reason it's not possible is because the client and server are both hardcoded to dismount vehicles on shift. Attempting to mount by right clicking with shift immediately dismounts anything you are riding.
