### ISSUE TITLE
Unable to trade due to right-click villagers

### ISSUE THREAD

**Issue by smmmadden** [BillyGalbreath/Ridables#6]
I went thru the configuration and didn't see an option to sneak right click or other ways.  Is there a key combo that allows the right-click to remain the trading with villager opton?  All I keep doing is end up riding the villager which is definitely not what I was looking for.  Thanks!

**Comment by BillyGalbreath** [comment]
Shift right click should work

**Comment by smmmadden** [comment]
looks like it was two separate issues.  I had updated the plugin but did not remove my config files and the latest updates were not there.  Once I deleted everything and restarted I was able to right click to mount, left shift to dismount and shift right click to trade.  - All's good now, thanks!

Any chance in adding another parameter to villagers that you can trade with to specify which way to mount and trade?  I'd like to retain the right click trade, but use shift right click to mount so users don't get confused.

**Comment by BillyGalbreath** [comment]
Sadly, requiring shift right click doesn't work well because as soon as you mount up you get dismounted from holding shift. Otherwise I would gladly implement that as a feature.

**Comment by SaltyAimbOtter** [comment]
Couldn't you just add a timer there? So you need to have ridden an entity for at least 1 second before you can dismount?
