### ISSUE TITLE
Add ridable vex

### ISSUE THREAD

**Issue by BillyGalbreath** [BillyGalbreath/Ridables#9]
This one is a tough one to design. The mob itself can clip through walls, but players can't.

So far my options seem to be

- let the mob and player both clip through walls with optional suffocation damage to player
- disable clipping through walls for the mob and player

Anyone have any better ideas?

**Comment by FrankHeijden** [comment]
set the player in gamemode 3 for clipping if they have a permission, otherwise let them not clip
